### PR TITLE
Makes verify-turnin work with python3 + other fixes

### PR DESCRIPTION
**Pull request by zakkak**
* Uses turnin's version as verify-turnin's version as well
* Checks for multiple `@` in verify-turnin's argument
* Adds info avout verify-turnin in man page
* Makes verify-turnin score 10/10 in pylint
* Ensures the necessary install directories exist

Supersedes #36

### CODE REVIEW

**Comment by zakkak** [comment]
@alx01011 can you please review this? I squashed your commits and did some additional minor changes.

**Review by alx01011 — APPROVED** [review]
Tested, everything works fine! Thank you:)

Side node, `_BSD_SOURCE` used in `turnin.c` is now deprecated. Instead, `_DEFAULT_SOURCE` can be used, since not only `verify-turnin` is being patched, I think this can be added too.

**Review by alx01011 — APPROVED** [review]

**Comment by zakkak** [comment]
> Side node, `_BSD_SOURCE` used in `turnin.c` is now deprecated. Instead, `_DEFAULT_SOURCE` can be used, since other fixes are also applied, I think this can be added too.

Sure the only reason I didn't do it is because I am not sure what glibc version is used on the University's systems. Can you [confirm that it's >= 2.19](https://sourceware.org/glibc/wiki/Release/2.20#Deprecation_of__BSD_SOURCE_and__SVID_SOURCE_feature_macros)?

**Comment by alx01011** [comment]
> > Side node, `_BSD_SOURCE` used in `turnin.c` is now deprecated. Instead, `_DEFAULT_SOURCE` can be used, since other fixes are also applied, I think this can be added too.
> 
> Sure the only reason I didn't do it is because I am not sure what glibc version is used on the University's systems. Can you [confirm that it's >= 2.19](https://sourceware.org/glibc/wiki/Release/2.20#Deprecation_of__BSD_SOURCE_and__SVID_SOURCE_feature_macros)?

I can confirm, every university computer is above glibc 2.19, [here](https://gist.github.com/alx01011/4454c0419c68b6df933521d6a29561a0) is the script result.

**Comment by zakkak** [comment]
@alx01011 and @daknob can you pleaes review https://github.com/zakkak/turnin/pull/37/commits/0320e93f32f87fd0767b55ca599a27eb06da1e8c as well?

Thanks

**Comment by alx01011** [comment]
> @alx01011 and @daknob can you pleaes review [0320e93](https://github.com/zakkak/turnin/commit/0320e93f32f87fd0767b55ca599a27eb06da1e8c) as well?
> 
> Thanks

Changes work as expected, signals are ignored, compiler is happy with `_DEFAULT_SOURCE`. 

_Side note:_ _It seems that the use of `signal()` [is not encouraged](https://linux.die.net/man/2/signal), though is more portable than **POSIX** `sigaction()`. Is this switch happening to ensure portability?_

**Comment by zakkak** [comment]
> _Side note:_ _It seems that the use of `signal()` [is not encouraged](https://linux.die.net/man/2/signal), though is more portable than **POSIX** `sigaction()`. Is this switch happening to guarantee portability?_

Good point. I was just following the advice from the GCC warning to "Use the signal function instead". I will switch it to using `sigaction` instead. Thanks!

**Comment by alx01011** [comment]
Lastly, I see there is a comment to use a **pager** in if a README file is present in assignment directory. Would executing `less` *(I had `execvp` in mind)* and providing the `README` file as an argument be ok for this?

**Comment by zakkak** [comment]
> Lastly, I see there is a comment to use a **pager** if a README file is present in assignment directory. Would executing `less` _(I had `execvp` in mind)_ and providing the `README` file as an argument be ok for this?
> 
> ```c
>          /*
> 	 * If there is a README file print it out.
> 	 * (someday use a pager)
> 	 */
> 	strcpy(assignment_file, "README");
> 	fd = fopen(assignment_path, "r");
> 	if (fd) {
> 		int c;
> 		fprintf(stderr, "*************** README **************\n");
> 		for (c = fgetc(fd); c != EOF; c = fgetc(fd)) {
> 			putchar(c);
> 		}
> 		fprintf(stderr, "*************************************\n");
> 		(void) fclose(fd);
> 		wanttocontinue();
> ```

I think we don't want something like this in order to minimize the risk of allowing an attacker to spawn arbitrary processes as root. @daknob please correct me if I am wrong.

**Comment by alx01011** [comment]
Good point. Forgot `turnin` has such permissions.

**Comment by daknob** [comment]
The current code (from line 533) seems to be running as class, e.g. `hy100`, so it's dangerous to run binaries as other users. The problem with `exec`* functions is also that they are dependent on the path of the binary. You can't just use `less` because someone with control to `$PATH` would be able to mask `less` to any binary they like, and have it executed as `hy100`, or any other user that may have a folder named `TURNIN` in their home directory, including `root`. If you specify the full path to `less` then you are dependent on its location and `turnin` will fail if there's a problem. Typically the file won't be world-writeable, but in theory someone who could write over this binary and have it also executed as class.

As a strategy, I would personally try to minimize the amount of time `turnin` spends as class (and especially as `root`) as it leaves it vulnerable. Typically a pager could be an infinite loop (waiting for the user to close it).

In addition to that, at least up to a few years ago, there were also machines which used 100% of a single core because they had stuck instances of `turnin` running (e.g. the user disconnected, etc.) which can happen when the binary is currently running as a different user.

Given the special considerations that a pager may have to security or reliability, I wouldn't personally put any work into that, because it's not as simple as it looks like.

**Comment by alx01011** [comment]
Thank you for the feedback, it's not even worth it then. 🥲 

Could one of the reason `turnin` hungs be that `SIGHUP` gets ignored? Shouldn't that case be handled differently?

**Comment by daknob** [comment]
If I remember correctly the problem is in `void wanttocontinue()` never getting an input. Now if it runs under a different user, I can see the issue. If it runs as the normal user, then perhaps. I think that when you exit the SSH session it's definitely a `SIGHUP` (hence the `nohup` command). But I don't know what happens if the session dies, etc.

I remember we had a problem that led us to ignore `SIGHUP` at the cost of this hanging issue, but I don't see which one it could be.

**Comment by zakkak** [comment]
A simple way to fix the issue with the stacked instances could be to spawn a thread that sleeps for say 5 or 10 minutes and exits the process one that time is over. I don't think there is any legitimate use of `turnin` requiring more time than that :)
Before doing any work on that though one should verify that this is still an issue...

So as far as this PR is concerned I think we all agree that it's ready to be merged, right?

**Comment by alx01011** [comment]
Agreed, this can be merged.

I was able to reproduce. Will continue on the issue's page.

**Pull request merged**
