### PR TITLE
Add support for late submissions

### PR DESCRIPTION
**Pull request by ru108**
Hello!

Explanation.

Class begin 27 July. Deadline 31 July after 17:00. Put file DUE (touch -d "30 July 2015 17:00").
1. Student submit work at Saturday 1 august before 17:00. He got 0 penalty.
2. Student submit work at Saturday 1 august after 17:00. He got penalty for week day(friday) 10%.
3. Student submit work at Sunday 2 august before 17:00. He got penalty for week day(friday) 10%.
4. Student submit work at Sunday 2 august after 17:00. He got penalty for week day(friday) 10% + 5% penalty for weekend(saturday).
5. Student submit work at Monday 3 august before 17:00. He got penalty for week day(friday) 10% + 5% penalty for weekend(saturday).
6. Student submit work at Monday 3 august after 17:00. He got penalty for week day(friday) 10% + 5% penalty for weekend(saturday) + 5% penalty for weekend(sunday).

### CODE REVIEW

**Comment by ru108** [comment]
yes
that correct
```
tmp_logs = (char *)malloc( (path_len + MAX_FILENAME_LENGTH) * sizeof(char) );
```

**Comment by ru108** [comment]
Yes, that more correct

**Comment by ru108** [comment]
That
```
if ( n <= 0 || n > 100 )
```

**Comment by DaKnOb** [comment]
Yes, you’re right. My mistake.

**Comment by zakkak** [comment]
I would like to see some documentation on any new functions (what they do, etc.) before merging any pull request.  Additionally, a commit message explaining the modifications and what they do (at high level) would be highly appreciated.

As I understand it you are creating two new folders (`on_time` and `late`) where you store log-files (one per submission).  Each log file has a name in the form of `<penalty>-substraction` and contains the log entry of the submission (`whichturnin, user, turnin number, date, time, number-of-files`).  This approach seems inappropriate since there is no straight-forward way to associate a submission archive (i.e. login-3.tgz with its corresponding log file).

What this patch essentially does is to create a split version of the logfile in multiple files grouped in two folders (`on_time` and `late`).  Unfortunately this does not look like what we need.  We would like to have the two folders and place the archives themselves in them according to when they got submitted.  Please correct me if I am wrong.

To be honest I do not really agree with the design proposed by @DaKnOb in #29.  I would prefer all the configuration to be in one file, lets say `LIMITS` (which we should really rename at some point).  Having extra files like DUE and LOCK seems counterintuitive.  I really liked your approach with `touch -d` though!

**Comment by ru108** [comment]
Hello! All user files arre stored in late and on_time dir. Add duedate and lockdate to LIMITS.

**Comment by zakkak** [comment]
Continuing in #32

**Pull request closed without merging**
